server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/madhukarGit/spring-cloud-config-server-repository
          default-label: main
          username: hmkaws428@gmail.com
          password: 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
          clone-on-start: true
    fail-fast: true
